spring:
  application:
    name: USER-MICROSERVICE_prod

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1011/eureka/prod
